/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsMap */

#ifndef _Included_io_realm_internal_OsMap
#define _Included_io_realm_internal_OsMap
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsMap_NOT_FOUND
#define io_realm_internal_OsMap_NOT_FOUND -1L
/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeCreate
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsMap_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetValue
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_OsMap_nativeGetValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetRealmAnyPtr
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeGetRealmAnyPtr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetRow
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeGetRow
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutNull
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutNull
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutLong
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutLong
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutFloat
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutBoolean
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutBoolean
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutDate
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutDate
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutDecimal128
 * Signature: (JLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutDecimal128
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutBinary
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutBinary
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutObjectId
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutObjectId
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutUUID
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutUUID
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutRealmAny
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutRealmAny
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativePutRow
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativePutRow
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsKey
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeRemove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativeRemove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeKeys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeKeys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeValues
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeValues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeFreeze
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeCreateAndPutEmbeddedObject
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMap_nativeCreateAndPutEmbeddedObject
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetEntryForModel
 * Signature: (JI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMap_nativeGetEntryForModel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetEntryForRealmAny
 * Signature: (JI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMap_nativeGetEntryForRealmAny
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeGetEntryForPrimitive
 * Signature: (JI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMap_nativeGetEntryForPrimitive
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsDouble
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsLong
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsBoolean
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsString
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsBinary
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsFloat
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsObjectId
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsObjectId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsUUID
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsUUID
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsDate
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsDecimal128
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsRealmAny
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsRealmAny
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeContainsRealmModel
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsMap_nativeContainsRealmModel
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeStartListening
 * Signature: (JLio/realm/internal/ObservableMap;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativeStartListening
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_realm_internal_OsMap
 * Method:    nativeStopListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsMap_nativeStopListening
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
