/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsResults */

#ifndef _Included_io_realm_internal_OsResults
#define _Included_io_realm_internal_OsResults
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsResults_AGGREGATE_FUNCTION_MINIMUM
#define io_realm_internal_OsResults_AGGREGATE_FUNCTION_MINIMUM 1L
#undef io_realm_internal_OsResults_AGGREGATE_FUNCTION_MAXIMUM
#define io_realm_internal_OsResults_AGGREGATE_FUNCTION_MAXIMUM 2L
#undef io_realm_internal_OsResults_AGGREGATE_FUNCTION_AVERAGE
#define io_realm_internal_OsResults_AGGREGATE_FUNCTION_AVERAGE 3L
#undef io_realm_internal_OsResults_AGGREGATE_FUNCTION_SUM
#define io_realm_internal_OsResults_AGGREGATE_FUNCTION_SUM 4L
#undef io_realm_internal_OsResults_MODE_EMPTY
#define io_realm_internal_OsResults_MODE_EMPTY 0L
#undef io_realm_internal_OsResults_MODE_TABLE
#define io_realm_internal_OsResults_MODE_TABLE 1L
#undef io_realm_internal_OsResults_MODE_LIST
#define io_realm_internal_OsResults_MODE_LIST 2L
#undef io_realm_internal_OsResults_MODE_QUERY
#define io_realm_internal_OsResults_MODE_QUERY 3L
#undef io_realm_internal_OsResults_MODE_TABLEVIEW
#define io_realm_internal_OsResults_MODE_TABLEVIEW 4L
/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeCreateResults
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeCreateResults
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeCreateSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeCreateSnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeFreeze
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeGetRow
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeGetRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeFirstRow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeFirstRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeLastRow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeLastRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeContains
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsResults_nativeContains
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeAggregate
 * Signature: (JJB)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_OsResults_nativeAggregate
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeStringDescriptor
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeStringDescriptor
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeDeleteFirst
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsResults_nativeDeleteFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeDeleteLast
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsResults_nativeDeleteLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeDelete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeDelete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetNull
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetNull
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetBoolean
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetBoolean
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetInt
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetInt
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetFloat
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetBinary
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetBinary
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetTimestamp
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetTimestamp
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetDecimal128
 * Signature: (JLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetDecimal128
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetObjectId
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetObjectId
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetUUID
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetUUID
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetObject
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetObject
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeSetList
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeSetList
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeStartListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeStartListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeStopListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeStopListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeGetTable
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeGetTable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeWhere
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeWhere
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    toJSON
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_OsResults_toJSON
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeIndexOf
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeIndexOf
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsResults_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeGetMode
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_io_realm_internal_OsResults_nativeGetMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeCreateResultsFromBacklinks
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsResults_nativeCreateResultsFromBacklinks
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeEvaluateQueryIfNeeded
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsResults_nativeEvaluateQueryIfNeeded
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsResults
 * Method:    nativeGetValue
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_OsResults_nativeGetValue
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
