/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsObject */

#ifndef _Included_io_realm_internal_OsObject
#define _Included_io_realm_internal_OsObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeStartListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsObject_nativeStartListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeStopListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsObject_nativeStopListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateNewObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateNewObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateRow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateNewObjectWithLongPrimaryKey
 * Signature: (JJJJZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateNewObjectWithLongPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateRowWithLongPrimaryKey
 * Signature: (JJJJZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateRowWithLongPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateNewObjectWithStringPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateNewObjectWithStringPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateRowWithStringPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateRowWithStringPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateRowWithObjectIdPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateRowWithObjectIdPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateNewObjectWithObjectIdPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateNewObjectWithObjectIdPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateRowWithUUIDPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateRowWithUUIDPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateNewObjectWithUUIDPrimaryKey
 * Signature: (JJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateNewObjectWithUUIDPrimaryKey
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObject
 * Method:    nativeCreateEmbeddedObject
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObject_nativeCreateEmbeddedObject
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
