/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsCollectionChangeSet */

#ifndef _Included_io_realm_internal_OsCollectionChangeSet
#define _Included_io_realm_internal_OsCollectionChangeSet
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsCollectionChangeSet_TYPE_DELETION
#define io_realm_internal_OsCollectionChangeSet_TYPE_DELETION 0L
#undef io_realm_internal_OsCollectionChangeSet_TYPE_INSERTION
#define io_realm_internal_OsCollectionChangeSet_TYPE_INSERTION 1L
#undef io_realm_internal_OsCollectionChangeSet_TYPE_MODIFICATION
#define io_realm_internal_OsCollectionChangeSet_TYPE_MODIFICATION 2L
#undef io_realm_internal_OsCollectionChangeSet_MAX_ARRAY_LENGTH
#define io_realm_internal_OsCollectionChangeSet_MAX_ARRAY_LENGTH 2147483639L
/*
 * Class:     io_realm_internal_OsCollectionChangeSet
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsCollectionChangeSet_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsCollectionChangeSet
 * Method:    nativeGetRanges
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_io_realm_internal_OsCollectionChangeSet_nativeGetRanges
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsCollectionChangeSet
 * Method:    nativeGetIndices
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_io_realm_internal_OsCollectionChangeSet_nativeGetIndices
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
