/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsSet */

#ifndef _Included_io_realm_internal_OsSet
#define _Included_io_realm_internal_OsSet
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsSet_NOT_FOUND
#define io_realm_internal_OsSet_NOT_FOUND -1L
#undef io_realm_internal_OsSet_VALUE_NOT_FOUND
#define io_realm_internal_OsSet_VALUE_NOT_FOUND 0L
#undef io_realm_internal_OsSet_VALUE_FOUND
#define io_realm_internal_OsSet_VALUE_FOUND 1L
/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeCreate
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeGetQuery
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeGetQuery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeDeleteAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSet_nativeDeleteAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeGetValueAtIndex
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_OsSet_nativeGetValueAtIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsBoolean
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsString
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsLong
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsFloat
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsDouble
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsBinary
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsDate
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsDecimal128
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsObjectId
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsObjectId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsUUID
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsUUID
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsRow
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsRealmAny
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsRealmAny
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddNull
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddBoolean
 * Signature: (JZ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddString
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddLong
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddFloat
 * Signature: (JF)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddDouble
 * Signature: (JD)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddBinary
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddDate
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddDecimal128
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddObjectId
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddObjectId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddUUID
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddUUID
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddRow
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddRealmAny
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeAddRealmAny
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveNull
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveBoolean
 * Signature: (JZ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveString
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveLong
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveFloat
 * Signature: (JF)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveDouble
 * Signature: (JD)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveBinary
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveDate
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveDecimal128
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveObjectId
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveObjectId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveUUID
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveUUID
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveRow
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveRealmAny
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSet_nativeRemoveRealmAny
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeGetRow
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeGetRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeGetRealmAny
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeGetRealmAny
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsAllRealmAnyCollection
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsAllRealmAnyCollection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeContainsAll
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeContainsAll
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeUnion
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeUnion
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAddAllRealmAnyCollection
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeAddAllRealmAnyCollection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeAsymmetricDifference
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeAsymmetricDifference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRemoveAllRealmAnyCollection
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeRemoveAllRealmAnyCollection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeIntersect
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeIntersect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeRetainAllRealmAnyCollection
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSet_nativeRetainAllRealmAnyCollection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSet_nativeClear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSet_nativeFreeze
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeStartListening
 * Signature: (JLio/realm/internal/ObservableSet;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSet_nativeStartListening
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_realm_internal_OsSet
 * Method:    nativeStopListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSet_nativeStopListening
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
