/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_RealmQuery */

#ifndef _Included_io_realm_RealmQuery
#define _Included_io_realm_RealmQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_RealmQuery
 * Method:    nativeSerializeQuery
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_RealmQuery_nativeSerializeQuery
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
