/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_UncheckedRow */

#ifndef _Included_io_realm_internal_UncheckedRow
#define _Included_io_realm_internal_UncheckedRow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetColumnCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetColumnCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetColumnKey
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetColumnKey
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetColumnNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_UncheckedRow_nativeGetColumnNames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetColumnType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_UncheckedRow_nativeGetColumnType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetObjectKey
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetObjectKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_UncheckedRow_nativeGetBoolean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_io_realm_internal_UncheckedRow_nativeGetFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_UncheckedRow_nativeGetDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetTimestamp
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetTimestamp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_UncheckedRow_nativeGetString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeIsNullLink
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_UncheckedRow_nativeIsNullLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetByteArray
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_realm_internal_UncheckedRow_nativeGetByteArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetDecimal128
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_UncheckedRow_nativeGetDecimal128
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetObjectId
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_UncheckedRow_nativeGetObjectId
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetUUID
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_UncheckedRow_nativeGetUUID
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetRealmAny
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetRealmAny
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetBoolean
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetFloat
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetLink
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetTimestamp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetTimestamp
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetByteArray
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetByteArray
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetDecimal128
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetDecimal128
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetObjectId
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetObjectId
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetUUID
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetUUID
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetRealmAny
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetRealmAny
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetLink
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetLink
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeNullifyLink
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeNullifyLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_UncheckedRow_nativeIsValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeHasColumn
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_UncheckedRow_nativeHasColumn
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeIsNull
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_UncheckedRow_nativeIsNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeSetNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_UncheckedRow_nativeSetNull
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeFreeze
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeCreateEmbeddedObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeCreateEmbeddedObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_UncheckedRow
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_UncheckedRow_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
