/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_objectstore_OsObjectBuilder */

#ifndef _Included_io_realm_internal_objectstore_OsObjectBuilder
#define _Included_io_realm_internal_objectstore_OsObjectBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStartSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStartSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStopSet
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStopSet
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddNullSetItem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddNullSetItem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddStringSetItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddStringSetItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddBooleanSetItem
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddBooleanSetItem
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddIntegerSetItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddIntegerSetItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddFloatSetItem
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddFloatSetItem
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDoubleSetItem
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDoubleSetItem
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddByteArraySetItem
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddByteArraySetItem
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDateSetItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDateSetItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDecimal128SetItem
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDecimal128SetItem
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectIdSetItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectIdSetItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddUUIDSetItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddUUIDSetItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeCreateBuilder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeCreateBuilder
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeDestroyBuilder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeDestroyBuilder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeCreateOrUpdateTopLevelObject
 * Signature: (JJJZZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeCreateOrUpdateTopLevelObject
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeUpdateEmbeddedObject
 * Signature: (JJJJZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeUpdateEmbeddedObject
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddNull
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddInteger
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddInteger
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddString
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddFloat
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddBoolean
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddByteArray
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDate
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObject
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObject
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDecimal128
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectId
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectId
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddUUID
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddUUID
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddRealmAny
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddRealmAny
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStartList
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStartList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStopList
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStopList
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddNullListItem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddNullListItem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddIntegerListItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddIntegerListItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddStringListItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddStringListItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddFloatListItem
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddFloatListItem
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDoubleListItem
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDoubleListItem
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddBooleanListItem
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddBooleanListItem
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddByteArrayListItem
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddByteArrayListItem
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDateListItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDateListItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDecimal128ListItem
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDecimal128ListItem
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectIdListItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectIdListItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddUUIDListItem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddUUIDListItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddRealmAnyListItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddRealmAnyListItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectListItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectListItem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectList
 * Signature: (JJ[J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectList
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStartDictionary
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStartDictionary
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeStopDictionary
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeStopDictionary
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddNullDictionaryEntry
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddNullDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddBooleanDictionaryEntry
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddBooleanDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddStringDictionaryEntry
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddStringDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddIntegerDictionaryEntry
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddIntegerDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDoubleDictionaryEntry
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDoubleDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddFloatDictionaryEntry
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddFloatDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddBinaryDictionaryEntry
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddBinaryDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDateDictionaryEntry
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDateDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddDecimal128DictionaryEntry
 * Signature: (JLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddDecimal128DictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectIdDictionaryEntry
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectIdDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddUUIDDictionaryEntry
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddUUIDDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddObjectDictionaryEntry
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddObjectDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsObjectBuilder
 * Method:    nativeAddRealmAnyDictionaryEntry
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsObjectBuilder_nativeAddRealmAnyDictionaryEntry
  (JNIEnv *, jclass, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
