/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsSharedRealm */

#ifndef _Included_io_realm_internal_OsSharedRealm
#define _Included_io_realm_internal_OsSharedRealm
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_ACCESS_ERROR
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_ACCESS_ERROR 0L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_BAD_HISTORY
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_BAD_HISTORY 1L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_PERMISSION_DENIED
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_PERMISSION_DENIED 2L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_EXISTS
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_EXISTS 3L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_NOT_FOUND
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_NOT_FOUND 4L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_INCOMPATIBLE_LOCK_FILE
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_INCOMPATIBLE_LOCK_FILE 5L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_FORMAT_UPGRADE_REQUIRED
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_KIND_FORMAT_UPGRADE_REQUIRED 6L
#undef io_realm_internal_OsSharedRealm_FILE_EXCEPTION_INCOMPATIBLE_SYNC_FILE
#define io_realm_internal_OsSharedRealm_FILE_EXCEPTION_INCOMPATIBLE_SYNC_FILE 7L
/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetSharedRealm
 * Signature: (JJJLio/realm/internal/RealmNotifier;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCloseSharedRealm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeCloseSharedRealm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeIsClosed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeIsClosed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeBeginTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeBeginTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCommitTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeCommitTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCancelTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeCancelTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeIsInTransaction
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeIsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeIsEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeRefresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeRefresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetVersionID
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetVersionID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetTableRef
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetTableRef
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCreateTable
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeCreateTable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCreateTableWithPrimaryKeyField
 * Signature: (JLjava/lang/String;Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeCreateTableWithPrimaryKeyField
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jboolean);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetTablesName
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetTablesName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeHasTable
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeHasTable
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeRenameTable
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeRenameTable
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeWriteCopy
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeWriteCopy
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeWaitForChange
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeWaitForChange
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeStopWaitForChange
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeStopWaitForChange
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeCompact
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeCompact
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeSetAutoRefresh
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeSetAutoRefresh
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeIsAutoRefresh
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeIsAutoRefresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetSchemaInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetSchemaInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeRegisterSchemaChangedCallback
 * Signature: (JLio/realm/internal/OsSharedRealm/SchemaChangedCallback;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsSharedRealm_nativeRegisterSchemaChangedCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeIsFrozen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsSharedRealm_nativeIsFrozen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeFreeze
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeFreeze
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeNumberOfVersions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeNumberOfVersions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetLatestSubscriptionSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetLatestSubscriptionSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsSharedRealm
 * Method:    nativeGetActiveSubscriptionSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSharedRealm_nativeGetActiveSubscriptionSet
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
