/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsSchemaInfo */

#ifndef _Included_io_realm_internal_OsSchemaInfo
#define _Included_io_realm_internal_OsSchemaInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_OsSchemaInfo
 * Method:    nativeCreateFromList
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSchemaInfo_nativeCreateFromList
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     io_realm_internal_OsSchemaInfo
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSchemaInfo_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsSchemaInfo
 * Method:    nativeGetObjectSchemaInfo
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsSchemaInfo_nativeGetObjectSchemaInfo
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
