/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsMapChangeSet */

#ifndef _Included_io_realm_internal_OsMapChangeSet
#define _Included_io_realm_internal_OsMapChangeSet
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsMapChangeSet_EMPTY_CHANGESET
#define io_realm_internal_OsMapChangeSet_EMPTY_CHANGESET 0L
/*
 * Class:     io_realm_internal_OsMapChangeSet
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsMapChangeSet_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsMapChangeSet
 * Method:    nativeGetStringKeyDeletions
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMapChangeSet_nativeGetStringKeyDeletions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMapChangeSet
 * Method:    nativeGetStringKeyInsertions
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMapChangeSet_nativeGetStringKeyInsertions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsMapChangeSet
 * Method:    nativeGetStringKeyModifications
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_OsMapChangeSet_nativeGetStringKeyModifications
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
