/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_objectstore_OsSubscription */

#ifndef _Included_io_realm_internal_objectstore_OsSubscription
#define _Included_io_realm_internal_objectstore_OsSubscription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeGetFinalizerMethodPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeGetFinalizerMethodPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeObjectClassName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeObjectClassName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeQueryString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeQueryString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeCreatedAt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeCreatedAt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscription
 * Method:    nativeUpdatedAt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscription_nativeUpdatedAt
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
