/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_objectstore_OsKeyPathMapping */

#ifndef _Included_io_realm_internal_objectstore_OsKeyPathMapping
#define _Included_io_realm_internal_objectstore_OsKeyPathMapping
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_objectstore_OsKeyPathMapping
 * Method:    nativeGetFinalizerMethodPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsKeyPathMapping_nativeGetFinalizerMethodPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_objectstore_OsKeyPathMapping
 * Method:    nativeCreateMapping
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsKeyPathMapping_nativeCreateMapping
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
