/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_TestUtil */

#ifndef _Included_io_realm_internal_TestUtil
#define _Included_io_realm_internal_TestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_TestUtil
 * Method:    getMaxExceptionNumber
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TestUtil_getMaxExceptionNumber
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_TestUtil
 * Method:    getExpectedMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_TestUtil_getExpectedMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_TestUtil
 * Method:    testThrowExceptions
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TestUtil_testThrowExceptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_TestUtil
 * Method:    getDateFromTimestamp
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TestUtil_getDateFromTimestamp
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
