/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_TableQuery */

#ifndef _Included_io_realm_internal_TableQuery
#define _Included_io_realm_internal_TableQuery
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_TableQuery_DEBUG
#define io_realm_internal_TableQuery_DEBUG 0L
/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeFind
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeFind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeSumInt
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeSumInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumInt
 * Signature: (JJ)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumInt
 * Signature: (JJ)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMinimumInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeAverageInt
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeAverageInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeSumFloat
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeSumFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumFloat
 * Signature: (JJ)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumFloat
 * Signature: (JJ)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMinimumFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeAverageFloat
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeAverageFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeSumRealmAny
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeSumRealmAny
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeSumDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeSumDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeSumDecimal128
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeSumDecimal128
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumDouble
 * Signature: (JJ)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumRealmAny
 * Signature: (JJ)Lio/realm/internal/core/NativeRealmAny;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumRealmAny
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumDecimal128
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeMaximumDecimal128
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumRealmAny
 * Signature: (JJ)Lio/realm/internal/core/NativeRealmAny;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMinimumRealmAny
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumDouble
 * Signature: (JJ)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMinimumDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumDecimal128
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeMinimumDecimal128
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeAverageRealmAny
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeAverageRealmAny
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeAverageDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_TableQuery_nativeAverageDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeAverageDecimal128
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_TableQuery_nativeAverageDecimal128
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMaximumTimestamp
 * Signature: (JJ)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMaximumTimestamp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeMinimumTimestamp
 * Signature: (JJ)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_TableQuery_nativeMinimumTimestamp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeRemove
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeRemove
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeRawPredicate
 * Signature: (JLjava/lang/String;[JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeRawPredicate
  (JNIEnv *, jobject, jlong, jstring, jlongArray, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeRawDescriptor
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeRawDescriptor
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeBeginGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeBeginGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeEndGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeEndGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeOr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeOr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeNot
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_TableQuery_nativeNot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeValidateQuery
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_TableQuery_nativeValidateQuery
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_TableQuery
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_TableQuery_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
