/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_core_NativeRealmAny */

#ifndef _Included_io_realm_internal_core_NativeRealmAny
#define _Included_io_realm_internal_core_NativeRealmAny
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateNull
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateNull
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateBoolean
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateBoolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateFloat
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateDouble
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateBinary
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateBinary
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsBinary
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsBinary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateDate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateDate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsDate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsDate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateObjectId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateObjectId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsObjectId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsObjectId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateDecimal128
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateDecimal128
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsDecimal128
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsDecimal128
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateUUID
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateUUID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeAsUUID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeAsUUID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeCreateLink
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeCreateLink
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeGetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeGetRealmModelTableName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeGetRealmModelTableName
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeGetRealmModelRowKey
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeGetRealmModelRowKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeEquals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeEquals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAny
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAny_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
