/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsObjectStore */

#ifndef _Included_io_realm_internal_OsObjectStore
#define _Included_io_realm_internal_OsObjectStore
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsObjectStore_SCHEMA_NOT_VERSIONED
#define io_realm_internal_OsObjectStore_SCHEMA_NOT_VERSIONED -1LL
/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeSetPrimaryKeyForObject
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsObjectStore_nativeSetPrimaryKeyForObject
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeGetPrimaryKeyForObject
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_OsObjectStore_nativeGetPrimaryKeyForObject
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeSetSchemaVersion
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsObjectStore_nativeSetSchemaVersion
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeGetSchemaVersion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObjectStore_nativeGetSchemaVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeDeleteTableForObject
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsObjectStore_nativeDeleteTableForObject
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObjectStore
 * Method:    nativeCallWithLock
 * Signature: (Ljava/lang/String;Ljava/lang/Runnable;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsObjectStore_nativeCallWithLock
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
