/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_log_LogLevel */

#ifndef _Included_io_realm_log_LogLevel
#define _Included_io_realm_log_LogLevel
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_log_LogLevel_ALL
#define io_realm_log_LogLevel_ALL 1L
#undef io_realm_log_LogLevel_TRACE
#define io_realm_log_LogLevel_TRACE 2L
#undef io_realm_log_LogLevel_DEBUG
#define io_realm_log_LogLevel_DEBUG 3L
#undef io_realm_log_LogLevel_INFO
#define io_realm_log_LogLevel_INFO 4L
#undef io_realm_log_LogLevel_WARN
#define io_realm_log_LogLevel_WARN 5L
#undef io_realm_log_LogLevel_ERROR
#define io_realm_log_LogLevel_ERROR 6L
#undef io_realm_log_LogLevel_FATAL
#define io_realm_log_LogLevel_FATAL 7L
#undef io_realm_log_LogLevel_OFF
#define io_realm_log_LogLevel_OFF 8L
/*
 * Class:     io_realm_log_LogLevel
 * Method:    forceJNIHeaderGeneration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_realm_log_LogLevel_forceJNIHeaderGeneration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
