/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_objectstore_OsSubscriptionSet */

#ifndef _Included_io_realm_internal_objectstore_OsSubscriptionSet
#define _Included_io_realm_internal_objectstore_OsSubscriptionSet
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_UNCOMMITTED
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_UNCOMMITTED 0L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_PENDING
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_PENDING 1L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_BOOTSTRAPPING
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_BOOTSTRAPPING 2L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_COMPLETE
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_COMPLETE 3L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_ERROR
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_ERROR 4L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_SUPERSEDED
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_SUPERSEDED 5L
#undef io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_AWAITING_MARK
#define io_realm_internal_objectstore_OsSubscriptionSet_STATE_VALUE_AWAITING_MARK 6L
/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeGetFinalizerMethodPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeGetFinalizerMethodPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeState
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeCreateMutableSubscriptionSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeCreateMutableSubscriptionSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeSubscriptionAt
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeSubscriptionAt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeWaitForSynchronization
 * Signature: (JLio/realm/internal/objectstore/OsSubscriptionSet/StateChangeCallback;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeWaitForSynchronization
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeFindByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeFindByName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeFindByQuery
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeFindByQuery
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsSubscriptionSet
 * Method:    nativeRefresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_objectstore_OsSubscriptionSet_nativeRefresh
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
