/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsList */

#ifndef _Included_io_realm_internal_OsList
#define _Included_io_realm_internal_OsList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeCreate
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_OsList_nativeCreate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeGetRow
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeGetRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddRow
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddRow
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertRow
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertRow
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetRow
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetRow
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeMove
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeMove
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeRemove
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeRemove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeRemoveAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeRemoveAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeGetQuery
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeGetQuery
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsList_nativeIsValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeDelete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeDelete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeDeleteAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeDeleteAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddNull
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddNull
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertNull
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetNull
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetNull
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertLong
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetLong
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertFloat
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetFloat
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddBoolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertBoolean
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetBoolean
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddBinary
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddBinary
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertBinary
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertBinary
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetBinary
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetBinary
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddDate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddDate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertDate
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertDate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetDate
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetDate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertString
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetString
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddDecimal128
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertDecimal128
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetDecimal128
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddObjectId
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddObjectId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertObjectId
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertObjectId
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetObjectId
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetObjectId
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddUUID
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddUUID
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertUUID
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertUUID
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetUUID
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetUUID
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeAddRealmAny
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeAddRealmAny
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeInsertRealmAny
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeInsertRealmAny
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeSetRealmAny
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeSetRealmAny
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeGetValue
 * Signature: (JJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_OsList_nativeGetValue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeStartListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeStartListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeStopListening
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsList_nativeStopListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeFreeze
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeCreateAndAddEmbeddedObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeCreateAndAddEmbeddedObject
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_OsList
 * Method:    nativeCreateAndSetEmbeddedObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsList_nativeCreateAndSetEmbeddedObject
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
