/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsObjectSchemaInfo */

#ifndef _Included_io_realm_internal_OsObjectSchemaInfo
#define _Included_io_realm_internal_OsObjectSchemaInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeCreateRealmObjectSchema
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeCreateRealmObjectSchema
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeAddProperties
 * Signature: (J[J[J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeAddProperties
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeGetClassName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeGetClassName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeGetProperty
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeGetProperty
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeGetPrimaryKeyProperty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeGetPrimaryKeyProperty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_OsObjectSchemaInfo
 * Method:    nativeIsEmbedded
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_OsObjectSchemaInfo_nativeIsEmbedded
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
