/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_core_NativeRealmAnyCollection */

#ifndef _Included_io_realm_internal_core_NativeRealmAnyCollection
#define _Included_io_realm_internal_core_NativeRealmAnyCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateBooleanCollection
 * Signature: ([Z[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateBooleanCollection
  (JNIEnv *, jclass, jbooleanArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateIntegerCollection
 * Signature: ([J[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateIntegerCollection
  (JNIEnv *, jclass, jlongArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateFloatCollection
 * Signature: ([F[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateFloatCollection
  (JNIEnv *, jclass, jfloatArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateDoubleCollection
 * Signature: ([D[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateDoubleCollection
  (JNIEnv *, jclass, jdoubleArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateStringCollection
 * Signature: ([Ljava/lang/String;[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateStringCollection
  (JNIEnv *, jclass, jobjectArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateBinaryCollection
 * Signature: ([[B[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateBinaryCollection
  (JNIEnv *, jclass, jobjectArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateDateCollection
 * Signature: ([J[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateDateCollection
  (JNIEnv *, jclass, jlongArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateObjectIdCollection
 * Signature: ([Ljava/lang/String;[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateObjectIdCollection
  (JNIEnv *, jclass, jobjectArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateDecimal128Collection
 * Signature: ([J[J[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateDecimal128Collection
  (JNIEnv *, jclass, jlongArray, jlongArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateUUIDCollection
 * Signature: ([Ljava/lang/String;[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateUUIDCollection
  (JNIEnv *, jclass, jobjectArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateObjectCollection
 * Signature: ([J[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateObjectCollection
  (JNIEnv *, jclass, jlongArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeCreateRealmAnyCollection
 * Signature: ([J[Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeCreateRealmAnyCollection
  (JNIEnv *, jclass, jlongArray, jbooleanArray);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeGetCollectionSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeGetCollectionSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeGetCollectionItem
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeGetCollectionItem
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_realm_internal_core_NativeRealmAnyCollection
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_core_NativeRealmAnyCollection_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
