/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_Property */

#ifndef _Included_io_realm_internal_Property
#define _Included_io_realm_internal_Property
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_Property_PRIMARY_KEY
#define io_realm_internal_Property_PRIMARY_KEY 1L
#undef io_realm_internal_Property_REQUIRED
#define io_realm_internal_Property_REQUIRED 1L
#undef io_realm_internal_Property_INDEXED
#define io_realm_internal_Property_INDEXED 1L
#undef io_realm_internal_Property_TYPE_INT
#define io_realm_internal_Property_TYPE_INT 0L
#undef io_realm_internal_Property_TYPE_BOOL
#define io_realm_internal_Property_TYPE_BOOL 1L
#undef io_realm_internal_Property_TYPE_STRING
#define io_realm_internal_Property_TYPE_STRING 2L
#undef io_realm_internal_Property_TYPE_DATA
#define io_realm_internal_Property_TYPE_DATA 3L
#undef io_realm_internal_Property_TYPE_DATE
#define io_realm_internal_Property_TYPE_DATE 4L
#undef io_realm_internal_Property_TYPE_FLOAT
#define io_realm_internal_Property_TYPE_FLOAT 5L
#undef io_realm_internal_Property_TYPE_DOUBLE
#define io_realm_internal_Property_TYPE_DOUBLE 6L
#undef io_realm_internal_Property_TYPE_OBJECT
#define io_realm_internal_Property_TYPE_OBJECT 7L
#undef io_realm_internal_Property_TYPE_LINKING_OBJECTS
#define io_realm_internal_Property_TYPE_LINKING_OBJECTS 8L
#undef io_realm_internal_Property_TYPE_DECIMAL128
#define io_realm_internal_Property_TYPE_DECIMAL128 11L
#undef io_realm_internal_Property_TYPE_OBJECT_ID
#define io_realm_internal_Property_TYPE_OBJECT_ID 10L
#undef io_realm_internal_Property_TYPE_UUID
#define io_realm_internal_Property_TYPE_UUID 12L
#undef io_realm_internal_Property_TYPE_MIXED
#define io_realm_internal_Property_TYPE_MIXED 9L
#undef io_realm_internal_Property_TYPE_REQUIRED
#define io_realm_internal_Property_TYPE_REQUIRED 0L
#undef io_realm_internal_Property_TYPE_NULLABLE
#define io_realm_internal_Property_TYPE_NULLABLE 64L
#undef io_realm_internal_Property_TYPE_ARRAY
#define io_realm_internal_Property_TYPE_ARRAY 128L
#undef io_realm_internal_Property_TYPE_SET
#define io_realm_internal_Property_TYPE_SET 256L
#undef io_realm_internal_Property_TYPE_DICTIONARY
#define io_realm_internal_Property_TYPE_DICTIONARY 512L
/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeCreatePersistedProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;IZZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeCreatePersistedProperty
  (JNIEnv *, jclass, jstring, jstring, jint, jboolean, jboolean);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeCreatePersistedLinkProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeCreatePersistedLinkProperty
  (JNIEnv *, jclass, jstring, jstring, jint, jstring);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeCreateComputedLinkProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeCreateComputedLinkProperty
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_Property_nativeGetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetColumnKey
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeGetColumnKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetLinkedObjectName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Property_nativeGetLinkedObjectName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
