/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_objectstore_OsMutableSubscriptionSet */

#ifndef _Included_io_realm_internal_objectstore_OsMutableSubscriptionSet
#define _Included_io_realm_internal_objectstore_OsMutableSubscriptionSet
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_UNCOMMITTED
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_UNCOMMITTED 0L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_PENDING
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_PENDING 1L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_BOOTSTRAPPING
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_BOOTSTRAPPING 2L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_COMPLETE
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_COMPLETE 3L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_ERROR
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_ERROR 4L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_SUPERSEDED
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_SUPERSEDED 5L
#undef io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_AWAITING_MARK
#define io_realm_internal_objectstore_OsMutableSubscriptionSet_STATE_VALUE_AWAITING_MARK 6L
/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeInsertOrAssign
 * Signature: (JLjava/lang/String;JZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeInsertOrAssign
  (JNIEnv *, jclass, jlong, jstring, jlong, jboolean);

/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeRemoveNamed
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeRemoveNamed
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeRemove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeRemove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeCommit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeCommit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeRemoveAll
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeRemoveAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_objectstore_OsMutableSubscriptionSet
 * Method:    nativeRemoveAllForType
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_objectstore_OsMutableSubscriptionSet_nativeRemoveAllForType
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
