/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_Table */

#ifndef _Included_io_realm_internal_Table
#define _Included_io_realm_internal_Table
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_Table_TABLE_NAME_MAX_LENGTH
#define io_realm_internal_Table_TABLE_NAME_MAX_LENGTH 63L
#undef io_realm_internal_Table_INFINITE
#define io_realm_internal_Table_INFINITE -1LL
#undef io_realm_internal_Table_NULLABLE
#define io_realm_internal_Table_NULLABLE 1L
#undef io_realm_internal_Table_NOT_NULLABLE
#define io_realm_internal_Table_NOT_NULLABLE 0L
#undef io_realm_internal_Table_NO_MATCH
#define io_realm_internal_Table_NO_MATCH -1L
#undef io_realm_internal_Table_MAX_BINARY_SIZE
#define io_realm_internal_Table_MAX_BINARY_SIZE 16777200L
#undef io_realm_internal_Table_MAX_STRING_SIZE
#define io_realm_internal_Table_MAX_STRING_SIZE 16777199L
/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeIsValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddColumn
 * Signature: (JILjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddColumn
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddPrimitiveListColumn
 * Signature: (JILjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddPrimitiveListColumn
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddPrimitiveDictionaryColumn
 * Signature: (JILjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddPrimitiveDictionaryColumn
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddPrimitiveSetColumn
 * Signature: (JILjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddPrimitiveSetColumn
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddColumnLink
 * Signature: (JILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddColumnLink
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddColumnDictionaryLink
 * Signature: (JILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddColumnDictionaryLink
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddColumnSetLink
 * Signature: (JILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeAddColumnSetLink
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeRenameColumn
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeRenameColumn
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeRemoveColumn
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeRemoveColumn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIsColumnNullable
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeIsColumnNullable
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeConvertColumnToNullable
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeConvertColumnToNullable
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeConvertColumnToNotNullable
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeConvertColumnToNotNullable
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeClear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetColumnCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetColumnCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetColumnName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Table_nativeGetColumnName
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetColumnNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_realm_internal_Table_nativeGetColumnNames
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetColumnKey
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetColumnKey
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetColumnType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_Table_nativeGetColumnType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeMoveLastOver
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeMoveLastOver
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetLong
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetBoolean
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeGetBoolean
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetFloat
 * Signature: (JJJ)F
 */
JNIEXPORT jfloat JNICALL Java_io_realm_internal_Table_nativeGetFloat
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetDouble
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_Table_nativeGetDouble
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetTimestamp
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetTimestamp
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetString
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Table_nativeGetString
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetByteArray
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_realm_internal_Table_nativeGetByteArray
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetLink
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetLink
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetLinkTarget
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetLinkTarget
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetDecimal128
 * Signature: (JJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_realm_internal_Table_nativeGetDecimal128
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetObjectId
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Table_nativeGetObjectId
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIsNull
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeIsNull
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetRowPtr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetRowPtr
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetLong
 * Signature: (JJJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetLong
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIncrementLong
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeIncrementLong
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetBoolean
 * Signature: (JJJZZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetBoolean
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetFloat
 * Signature: (JJJFZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetFloat
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetDouble
 * Signature: (JJJDZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetDouble
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetTimestamp
 * Signature: (JJJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetTimestamp
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetString
 * Signature: (JJJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetString
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetNull
 * Signature: (JJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetNull
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetByteArray
 * Signature: (JJJ[BZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetByteArray
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetDecimal128
 * Signature: (JJJJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetObjectId
 * Signature: (JJJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetObjectId
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetUUID
 * Signature: (JJJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetUUID
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetLink
 * Signature: (JJJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetLink
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetRealmAny
 * Signature: (JJJJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeSetRealmAny
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeAddSearchIndex
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeAddSearchIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeRemoveSearchIndex
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeRemoveSearchIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeHasSearchIndex
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeHasSearchIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIsNullLink
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeIsNullLink
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeNullifyLink
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Table_nativeNullifyLink
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeCountLong
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeCountLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeCountFloat
 * Signature: (JJF)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeCountFloat
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeCountDouble
 * Signature: (JJD)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeCountDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeCountString
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeCountString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeWhere
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeWhere
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstInt
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstInt
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstBool
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstBool
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstFloat
 * Signature: (JJF)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstFloat
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstDouble
 * Signature: (JJD)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstTimestamp
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstTimestamp
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstString
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstString
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstDecimal128
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstDecimal128
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstObjectId
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstObjectId
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstUUID
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstUUID
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFindFirstNull
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFindFirstNull
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Table_nativeGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeHasSameSchema
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeHasSameSchema
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeFreeze
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Table_nativeFreeze
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeIsEmbedded
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeIsEmbedded
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Table
 * Method:    nativeSetEmbedded
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Table_nativeSetEmbedded
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
