/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_log_RealmLog */

#ifndef _Included_io_realm_log_RealmLog
#define _Included_io_realm_log_RealmLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeAddLogger
 * Signature: (Lio/realm/log/RealmLogger;)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeAddLogger
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeRemoveLogger
 * Signature: (Lio/realm/log/RealmLogger;)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeRemoveLogger
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeClearLoggers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeClearLoggers
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeRegisterDefaultLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeRegisterDefaultLogger
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeLog
 * Signature: (ILjava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeLog
  (JNIEnv *, jclass, jint, jstring, jthrowable, jstring);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeSetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeSetLogLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeGetLogLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_realm_log_RealmLog_nativeGetLogLevel
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeCreateCoreLoggerBridge
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_log_RealmLog_nativeCreateCoreLoggerBridge
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeCloseCoreLoggerBridge
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeCloseCoreLoggerBridge
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_log_RealmLog
 * Method:    nativeLogToCoreLoggerBridge
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_log_RealmLog_nativeLogToCoreLoggerBridge
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
