/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_OsRealmConfig */

#ifndef _Included_io_realm_internal_OsRealmConfig
#define _Included_io_realm_internal_OsRealmConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_AUTOMATIC
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_AUTOMATIC 0L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_IMMUTABLE
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_IMMUTABLE 1L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_READONLY
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_READONLY 2L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_SOFT_RESET_FILE
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_SOFT_RESET_FILE 3L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_ADDITIVE_DISCOVERED
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_ADDITIVE_DISCOVERED 5L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_ADDITIVE_EXPLICIT
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_ADDITIVE_EXPLICIT 6L
#undef io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_MANUAL
#define io_realm_internal_OsRealmConfig_SCHEMA_MODE_VALUE_MANUAL 7L
#undef io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_IMMEDIATELY
#define io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_IMMEDIATELY 0L
#undef io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_LIVE_INDEFINETELY
#define io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_LIVE_INDEFINETELY 1L
#undef io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_AFTER_CHANGES_UPLOADED
#define io_realm_internal_OsRealmConfig_SYNCSESSION_STOP_POLICY_VALUE_AFTER_CHANGES_UPLOADED 2L
#undef io_realm_internal_OsRealmConfig_PROXYCONFIG_TYPE_VALUE_HTTP
#define io_realm_internal_OsRealmConfig_PROXYCONFIG_TYPE_VALUE_HTTP 0L
#undef io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_MANUAL
#define io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_MANUAL 0L
#undef io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_DISCARD_LOCAL
#define io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_DISCARD_LOCAL 1L
#undef io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_RECOVER
#define io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_RECOVER 2L
#undef io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_RECOVER_OR_DISCARD
#define io_realm_internal_OsRealmConfig_CLIENT_RESYNC_MODE_RECOVER_OR_DISCARD 3L
/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsRealmConfig_nativeCreate
  (JNIEnv *, jclass, jstring, jstring, jboolean, jlong);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetEncryptionKey
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetEncryptionKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetInMemory
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetInMemory
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetSchemaConfig
 * Signature: (JBJJLio/realm/internal/OsSharedRealm/MigrationCallback;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetSchemaConfig
  (JNIEnv *, jobject, jlong, jbyte, jlong, jlong, jobject);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetCompactOnLaunchCallback
 * Signature: (JLio/realm/CompactOnLaunchCallback;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetCompactOnLaunchCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetInitializationCallback
 * Signature: (JLio/realm/internal/OsSharedRealm/InitializationCallback;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetInitializationCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeEnableChangeNotification
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeEnableChangeNotification
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeCreateAndSetSyncConfig
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;BLjava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_OsRealmConfig_nativeCreateAndSetSyncConfig
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jbyte, jstring, jstring, jobjectArray, jbyte, jobject, jobject, jstring, jobject);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetSyncConfigSslSettings
 * Signature: (JZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetSyncConfigSslSettings
  (JNIEnv *, jclass, jlong, jboolean, jstring);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeSetSyncConfigProxySettings
 * Signature: (JBLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_OsRealmConfig_nativeSetSyncConfigProxySettings
  (JNIEnv *, jclass, jlong, jbyte, jstring, jint);

/*
 * Class:     io_realm_internal_OsRealmConfig
 * Method:    nativeGetFinalizerPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_OsRealmConfig_nativeGetFinalizerPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
