/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_Util */

#ifndef _Included_io_realm_internal_Util
#define _Included_io_realm_internal_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_Util
 * Method:    nativeGetTablePrefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Util_nativeGetTablePrefix
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
