import org.apache.tools.ant.filters.ReplaceTokens

buildscript {
    def properties = new Properties()
    properties.load(new FileInputStream("${rootDir}/../dependencies.list"))
    ext.kotlin_version = properties.get('KOTLIN')
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'groovy'
apply plugin: 'java-gradle-plugin'
apply plugin: 'maven-publish'

def props = new Properties()
props.load(new FileInputStream("${rootDir}/../dependencies.list"))
props.each { key, val ->
    project.ext.set(key, val)
}

repositories {
    if (project.hasProperty('g008StagingRepository')) {
        maven {
            url project.getProperty('g008StagingRepository')
            content { includeGroup 'io.github.leminity.realm' }
        }
    }
    mavenLocal()
    google()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

group = 'io.github.leminity.realm'
version = file("${projectDir}/../version.txt").text.trim()

configurations {
    provided
    compile.extendsFrom provided
}

test {
    testLogging.showStandardStreams = true
}

sourceSets {
    main {
        compileClasspath += configurations.provided
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation "io.github.leminity.realm:realm-transformer:${version}"
    runtimeOnly "com.android.tools.build:gradle-kotlin:${props.get("GRADLE_BUILD_TOOLS")}"
    compileOnly "com.android.tools.build:gradle:${props.get("GRADLE_BUILD_TOOLS")}"

    testImplementation gradleTestKit()
    testImplementation 'junit:junit:4.12'
    testImplementation "com.android.tools.build:gradle:${props.get("GRADLE_BUILD_TOOLS")}"
}

test {
    systemProperty 'realmPluginClasspath', sourceSets.main.runtimeClasspath.asPath
}

task generateVersionClass(type: Copy) {
    from 'src/main/templates/Version.kt'
    into 'build/generated-src/main/kotlin/io/realm/gradle'
    filter(ReplaceTokens, tokens: [version: version])
    doFirst {
        delete 'build/generated-src/main/kotlin/io/realm/Version.kt'
    }
    outputs.upToDateWhen { false }
}

// Include the generated Version file
sourceSets {
    main {
        java {
            srcDirs += ['build/generated-src/main/kotlin']
        }
    }
}

compileKotlin.dependsOn generateVersionClass

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
}

apply from: "${rootDir}/../mavencentral-publications.gradle"

publishing {
    publications {
        realm(MavenPublication) {
            groupId 'io.github.leminity.realm'
            artifactId = 'realm-gradle-plugin'
            from components.java
            populatePom(
                    it,
                    'realm-gradle-plugin',
                    'Gradle plugin for Realm. Realm is a mobile database: Build better apps, faster.'
            )
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.named('sourcesJar').configure {
    dependsOn generateVersionClass
}
