// Modified by Leminity from the upstream Realm Java project.
buildscript {
    def properties = new Properties()
    properties.load(new FileInputStream("${projectDir}/../dependencies.list"))
    ext.kotlin_version = properties.get('KOTLIN')
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'io.github.leminity.realm'
version = file("${projectDir}/../version.txt").text.trim()

def properties = new Properties()
properties.load(new FileInputStream("${projectDir}/../dependencies.list"))

def coreVersion = properties.getProperty('REALM_CORE')

repositories {
    if (project.hasProperty('g008StagingRepository')) {
        maven {
            url project.getProperty('g008StagingRepository')
            content { includeGroup 'io.github.leminity.realm' }
        }
    }
    mavenLocal()
    google()
    mavenCentral()
}

configurations {
    provided
    compile.extendsFrom provided
}

// Include the generated Version file
sourceSets {
    main {
        compileClasspath += configurations.provided
        java.srcDirs += ['build/generated-src/main/java', 'src/main/kotlin']
    }
}

dependencies {
    implementation gradleApi()
    implementation "io.github.leminity.realm:realm-annotations:${version}"
    compileOnly "com.android.tools.build:gradle:${properties.get("GRADLE_BUILD_TOOLS")}"
    implementation 'org.javassist:javassist:3.25.0-GA'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}"
    implementation "com.google.guava:guava:31.0.1-jre"
    // JAX-B dependencies for JDK 9+ (this is not available in JVM env 'java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter'
    // and it was removed in Java 11 https://stackoverflow.com/a/43574427
    implementation("javax.xml.bind:jaxb-api:2.3.1")

    testImplementation 'junit:junit:4.12'
}

// for Ant filter
import org.apache.tools.ant.filters.ReplaceTokens

task generateVersionClass(type: Copy) {
    from 'src/main/templates/Version.java'
    into 'build/generated-src/main/java/io/realm/transformer'
    filter(ReplaceTokens, tokens: [version: version, coreVersion: coreVersion])
    outputs.upToDateWhen { false }
}

compileKotlin.dependsOn generateVersionClass

apply from: "${rootDir}/../mavencentral-publications.gradle"

publishing {
    publications {
        realm(MavenPublication) {
            groupId 'io.github.leminity.realm'
            artifactId = 'realm-transformer'
            from components.java
            populatePom(
                    it,
                    'realm-transformer',
                    'Android Gradle Transformer for Realm. Realm is a mobile database: Build better apps, faster.'
            )
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.named('sourcesJar') {
    dependsOn generateVersionClass
}

compileKotlin {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
        freeCompilerArgs = ["-Xinline-classes", "-Xjvm-default=all-compatibility"]
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
}
