buildscript {
    def projectDependencies = new Properties()
    projectDependencies.load(new FileInputStream("${rootDir}/../dependencies.list"))
    def forkRepositoryUrl = gradle.startParameter.projectProperties.get('forkRepositoryUrl')
    def distributionGroup = gradle.startParameter.projectProperties.get('forkGroup') ?: 'io.realm'
    def distributionVersion = gradle.startParameter.projectProperties.get('forkVersion') ?: file('../version.txt').text.trim()
    ext.kotlin_version = projectDependencies.get('KOTLIN')
    ext.coroutines_android_version = projectDependencies.get('KOTLIN_COROUTINES')
    ext.dokka_version = '1.5.0'
    repositories {
        if (forkRepositoryUrl) {
            maven { url uri(forkRepositoryUrl) }
        }
        if (!forkRepositoryUrl) {
            mavenLocal()
        }
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:${projectDependencies.get('GRADLE_BUILD_TOOLS')}"
        classpath 'de.undercouch:gradle-download-task:4.0.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        classpath 'com.github.skhatri:gradle-s3-plugin:1.0.4'
        classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.8.2'
        classpath "${distributionGroup}:realm-transformer:${distributionVersion}"
        classpath "${distributionGroup}:realm-library-build-transformer:${distributionVersion}"
        classpath 'net.ltgt.gradle:gradle-errorprone-plugin:2.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:${dokka_version}"
        classpath "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.5.0"
        classpath "io.github.gradle-nexus:publish-plugin:${projectDependencies.get("GRADLE_NEXUS_PLUGIN")}"
    }
}

allprojects {
    def projectDependencies = new Properties()
    projectDependencies.load(new FileInputStream("${rootDir}/../dependencies.list"))
    projectDependencies.each { key, val ->
        project.ext.set(key, val)
    }
    project.ext.minSdkVersion = 21
    project.ext.compileSdkVersion = 37
    project.ext.buildToolsVersion = projectDependencies.get("ANDROID_BUILD_TOOLS")
    group = project.findProperty('forkGroup') ?: 'io.realm'
    version = project.findProperty('forkVersion') ?: file("${rootDir}/../version.txt").text.trim()
    repositories {
        if (project.hasProperty('forkRepositoryUrl')) {
            maven { url uri(project.property('forkRepositoryUrl')) }
        }
        if (!project.hasProperty('forkRepositoryUrl')) {
            mavenLocal()
        }
        google()
        mavenCentral()
    }
}

// Disable JavaDoc strict mode: https://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html
if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:-missing', '-quiet')
        }
    }
}

if (project.hasProperty('enableMavenCentralPublishing')) {
    apply from: "${rootDir}/../mavencentral-publish.gradle"
}

if (project.hasProperty('forkRepositoryUrl')) {
    gradle.projectsEvaluated {
        def realmLibraryPublication = project(':realm-library').tasks.getByName(
                'publishBasePublicationPublicationToForkRepository')
        def annotationsProcessorPublication = project(':realm-annotations-processor').tasks.getByName(
                'publishBasePublicationPublicationToForkRepository')
        def kotlinExtensionsPublication = project(':kotlin-extensions').tasks.getByName(
                'publishBasePublicationPublicationToForkRepository')

        annotationsProcessorPublication.mustRunAfter(realmLibraryPublication)
        kotlinExtensionsPublication.mustRunAfter(annotationsProcessorPublication)
    }
}
