#!/usr/bin/env python3
"""Validate and package the local-only G008 six-artifact Maven repository.

This tool intentionally has no network or credential support. It verifies the
Maven layout generated by Gradle, writes required checksums, emits a normalized
manifest, and optionally creates a byte-stable Central-format zip bundle.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Iterable
from xml.etree import ElementTree


GROUP = "io.github.leminity.realm"
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
VERSION = (REPOSITORY_ROOT / "version.txt").read_text(encoding="utf-8").strip()
if not VERSION:
    raise RuntimeError("version.txt must contain the G008 release version")
ARTIFACTS = {
    "realm-gradle-plugin": "jar",
    "realm-transformer": "jar",
    "realm-annotations": "jar",
    "realm-annotations-processor": "jar",
    "realm-android-library": "aar",
    "realm-android-kotlin-extensions": "aar",
}
ANDROID_ABIS = frozenset(("armeabi-v7a", "arm64-v8a", "x86_64"))
FORK_EDGES = {
    "realm-gradle-plugin": {("realm-transformer", VERSION)},
    "realm-transformer": {("realm-annotations", VERSION)},
    "realm-annotations": set(),
    "realm-annotations-processor": {("realm-annotations", VERSION)},
    "realm-android-library": {("realm-annotations", VERSION)},
    # The upstream POM intentionally omits realm-library. The Gradle plugin
    # injects it at consumer configuration time.
    "realm-android-kotlin-extensions": set(),
}
CHECKSUMS = ("md5", "sha1", "sha256", "sha512")
DENYLIST = ("objectserver", "static.realm.io", "oss.sonatype", "s3://")
SECRET_MARKERS = (
    b"-----BEGIN PGP PRIVATE KEY BLOCK-----",
    b"ossrhPassword",
    b"sonatypeUsername",
    b"sonatypePassword",
)


class ValidationError(RuntimeError):
    """Raised when a Central bundle invariant is not satisfied."""


def digest(path: Path, algorithm: str) -> str:
    value = hashlib.new(algorithm)
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def coordinate_directory(repository: Path, artifact: str) -> Path:
    return repository / "io" / "github" / "leminity" / "realm" / artifact / VERSION


def expected_deployables(artifact: str, extension: str) -> set[str]:
    stem = f"{artifact}-{VERSION}"
    return {
        f"{stem}.{extension}",
        f"{stem}.pom",
        f"{stem}-sources.jar",
        f"{stem}-javadoc.jar",
    }


def parse_pom(pom: Path) -> list[dict[str, object]]:
    try:
        root = ElementTree.parse(pom).getroot()
    except ElementTree.ParseError as error:
        raise ValidationError(f"invalid POM XML {pom}: {error}") from error

    def child_text(node: ElementTree.Element, name: str) -> str:
        for child in node:
            if child.tag.rsplit("}", 1)[-1] == name:
                return (child.text or "").strip()
        return ""

    dependencies: list[dict[str, object]] = []
    for node in root.iter():
        if node.tag.rsplit("}", 1)[-1] != "dependency":
            continue
        exclusions: list[tuple[str, str]] = []
        for child in node.iter():
            if child.tag.rsplit("}", 1)[-1] != "exclusion":
                continue
            exclusions.append((child_text(child, "groupId"), child_text(child, "artifactId")))
        dependencies.append(
            {
                "groupId": child_text(node, "groupId"),
                "artifactId": child_text(node, "artifactId"),
                "version": child_text(node, "version"),
                "scope": child_text(node, "scope") or "compile",
                "exclusions": sorted(exclusions),
            }
        )
    return sorted(
        dependencies,
        key=lambda dependency: (
            str(dependency["groupId"]),
            str(dependency["artifactId"]),
            str(dependency["version"]),
            str(dependency["scope"]),
            dependency["exclusions"],
        ),
    )


def validate_pom_metadata(pom: Path, artifact: str) -> None:
    root = ElementTree.parse(pom).getroot()

    def find_text(name: str) -> str:
        for node in root.iter():
            if node.tag.rsplit("}", 1)[-1] == name:
                return (node.text or "").strip()
        return ""

    required = {
        "groupId": GROUP,
        "artifactId": artifact,
        "version": VERSION,
        "url": "https://github.com/Leminity/realm-java",
    }
    for key, expected in required.items():
        actual = find_text(key)
        if actual != expected:
            raise ValidationError(f"{pom}: expected {key}={expected!r}, found {actual!r}")
    contents = pom.read_text(encoding="utf-8").lower()
    for denied in DENYLIST:
        if denied in contents:
            raise ValidationError(f"{pom}: denied release endpoint/reference {denied!r}")
    if "io.realm" in contents:
        raise ValidationError(f"{pom}: legacy io.realm dependency remains")
    if "leminity" not in contents:
        raise ValidationError(f"{pom}: fork developer metadata is missing")
    if "apache software license" not in contents:
        raise ValidationError(f"{pom}: Apache-2.0 metadata is missing")


def validate_fork_edges(artifact: str, dependencies: list[dict[str, object]]) -> None:
    actual = {
        (str(dependency["artifactId"]), str(dependency["version"]))
        for dependency in dependencies
        if dependency["groupId"] == GROUP
    }
    expected = FORK_EDGES[artifact]
    if actual != expected:
        raise ValidationError(
            f"{artifact}: fork POM edges differ; expected {sorted(expected)}, got {sorted(actual)}"
        )


def deployment_files(directory: Path) -> list[Path]:
    return sorted(path for path in directory.iterdir() if path.is_file())


def validate_payload(path: Path) -> None:
    contents = path.read_bytes()
    for marker in SECRET_MARKERS:
        if marker in contents:
            raise ValidationError(f"{path}: release payload contains a credential/private-key marker")


def validate_base_library_aar(path: Path) -> None:
    """Keep the public native payload to the exact non-x86 Realm ABI set."""
    try:
        with zipfile.ZipFile(path) as archive:
            entries = archive.namelist()
    except zipfile.BadZipFile as error:
        raise ValidationError(f"invalid realm-android-library AAR {path}: {error}") from error
    abis = {
        entry.split("/", 2)[1]
        for entry in entries
        if entry.startswith("jni/") and len(entry.split("/", 2)) >= 3
    }
    if abis != ANDROID_ABIS:
        raise ValidationError(
            f"{path}: JNI ABI directories must be {sorted(ANDROID_ABIS)}, got {sorted(abis)}"
        )
    for abi in ANDROID_ABIS:
        if not any(entry.startswith(f"jni/{abi}/") and entry.endswith(".so") for entry in entries):
            raise ValidationError(f"{path}: JNI ABI {abi} has no native library")


def write_checksums(repository: Path) -> None:
    # Gradle file repositories emit mutable maven-metadata files. They are not
    # release-version inputs and are excluded from the immutable Central bundle.
    for metadata in repository.rglob("maven-metadata.xml*"):
        metadata.unlink()
    for artifact, extension in ARTIFACTS.items():
        directory = coordinate_directory(repository, artifact)
        deployables = expected_deployables(artifact, extension)
        # Gradle's file publisher can emit checksums for detached signatures
        # and even checksum sidecars. Central inputs checksum the four actual
        # deployables only, so prune every pre-existing checksum that does not
        # immediately belong to one of those files before rebuilding them.
        for sidecar in directory.iterdir():
            if not sidecar.is_file():
                continue
            for algorithm in CHECKSUMS:
                suffix = f".{algorithm}"
                if sidecar.name.endswith(suffix) and sidecar.name[: -len(suffix)] not in deployables:
                    sidecar.unlink()
                    break
        for name in deployables:
            source = directory / name
            if not source.is_file():
                raise ValidationError(f"cannot checksum missing deployable {source}")
            for algorithm in CHECKSUMS:
                (directory / f"{name}.{algorithm}").write_text(
                    digest(source, algorithm) + "\n", encoding="ascii"
                )


def validate_checksums(directory: Path, deployables: Iterable[str]) -> None:
    for name in deployables:
        source = directory / name
        for algorithm in CHECKSUMS:
            checksum = directory / f"{name}.{algorithm}"
            if not checksum.is_file():
                raise ValidationError(f"missing {algorithm} checksum for {source}")
            if checksum.read_text(encoding="ascii").strip() != digest(source, algorithm):
                raise ValidationError(f"invalid {algorithm} checksum for {source}")


def validate_signatures(directory: Path, deployables: Iterable[str]) -> None:
    """Require detached signatures that GnuPG can verify locally.

    The verifier deliberately accepts no key material or network configuration.
    A caller that uses an ephemeral key supplies its existing keyring through
    ``G008_GPG_HOMEDIR``; otherwise the current user's local keyring is used.
    """
    command_prefix = ["gpg", "--batch", "--no-tty"]
    homedir = os.environ.get("G008_GPG_HOMEDIR")
    if homedir:
        command_prefix.extend(["--homedir", homedir])
    for name in deployables:
        source = directory / name
        signature = directory / f"{name}.asc"
        if not signature.is_file():
            raise ValidationError(f"missing PGP signature for {source}")
        result = subprocess.run(
            [*command_prefix, "--verify", str(signature), str(source)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode:
            details = (result.stderr or result.stdout).strip().splitlines()
            summary = details[-1] if details else f"gpg exited {result.returncode}"
            raise ValidationError(f"invalid PGP signature for {source}: {summary}")


def validate_plugin_injection(plugin_source: Path | None) -> list[dict[str, str]]:
    edges = [
        {"artifactId": "realm-annotations", "kind": "annotation-api"},
        {"artifactId": "realm-annotations-processor", "kind": "annotation-processor"},
        {"artifactId": "realm-android-library", "kind": "base-library"},
        {"artifactId": "realm-android-kotlin-extensions", "kind": "kotlin-extension"},
    ]
    if plugin_source is None:
        return edges
    if not plugin_source.is_file():
        raise ValidationError(f"plugin source does not exist: {plugin_source}")
    source = plugin_source.read_text(encoding="utf-8")
    if f'FORK_GROUP = "{GROUP}"' not in source:
        raise ValidationError("Realm plugin does not define the required fork group")
    for edge in edges:
        if edge["artifactId"] not in source:
            raise ValidationError(f"Realm plugin is missing dynamic injection for {edge['artifactId']}")
    if "io.realm:" in source:
        raise ValidationError("Realm plugin still injects legacy io.realm coordinates")
    return edges


def validate_repository(repository: Path, require_signatures: bool, plugin_source: Path | None) -> dict[str, object]:
    if not repository.is_dir():
        raise ValidationError(f"repository directory does not exist: {repository}")
    graph: dict[str, list[dict[str, object]]] = {}
    artifact_inventory: dict[str, list[str]] = {}
    for artifact, extension in ARTIFACTS.items():
        directory = coordinate_directory(repository, artifact)
        if not directory.is_dir():
            raise ValidationError(f"missing coordinate directory {directory}")
        deployables = expected_deployables(artifact, extension)
        names = {path.name for path in deployment_files(directory)}
        missing = deployables - names
        if missing:
            raise ValidationError(f"{artifact}: missing deployables {sorted(missing)}")
        allowed = set(deployables)
        allowed.update(f"{name}.{checksum}" for name in deployables for checksum in CHECKSUMS)
        allowed.update(f"{name}.asc" for name in deployables)
        unexpected = names - allowed
        if unexpected:
            raise ValidationError(f"{artifact}: unexpected classifiers/files {sorted(unexpected)}")
        for name in names:
            lowered = name.lower()
            if "x86" in lowered or "sync" in lowered or "objectserver" in lowered:
                raise ValidationError(f"{artifact}: denied release payload {name}")
        for name in deployables:
            validate_payload(directory / name)
        if artifact == "realm-android-library":
            validate_base_library_aar(directory / f"{artifact}-{VERSION}.{extension}")
        if require_signatures:
            validate_signatures(directory, deployables)
        validate_checksums(directory, deployables)
        pom = directory / f"{artifact}-{VERSION}.pom"
        validate_pom_metadata(pom, artifact)
        dependencies = parse_pom(pom)
        validate_fork_edges(artifact, dependencies)
        graph[artifact] = dependencies
        artifact_inventory[artifact] = sorted(names)

    expected_directories = {coordinate_directory(repository, artifact).resolve() for artifact in ARTIFACTS}
    all_files = sorted(path for path in repository.rglob("*") if path.is_file())
    for path in all_files:
        if not any(parent in path.resolve().parents for parent in expected_directories):
            raise ValidationError(f"unexpected path outside exact-six coordinates: {path.relative_to(repository)}")

    return {
        "coordinates": [f"{GROUP}:{artifact}:{VERSION}" for artifact in ARTIFACTS],
        "artifacts": artifact_inventory,
        "normalized_pom_dependencies": graph,
        "dynamic_plugin_injection": validate_plugin_injection(plugin_source),
    }


def write_manifest(path: Path, repository: Path, report: dict[str, object]) -> None:
    files: list[dict[str, object]] = []
    for source in sorted(candidate for candidate in repository.rglob("*") if candidate.is_file()):
        files.append(
            {
                "path": source.relative_to(repository).as_posix(),
                "sha256": digest(source, "sha256"),
                "size": source.stat().st_size,
            }
        )
    output = {
        "format": "g008-local-maven-central-inputs-v1",
        "group": GROUP,
        "version": VERSION,
        "files": files,
        **report,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_bundle(path: Path, repository: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as bundle:
        for source in sorted(candidate for candidate in repository.rglob("*") if candidate.is_file()):
            info = zipfile.ZipInfo(source.relative_to(repository).as_posix(), date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            bundle.writestr(info, source.read_bytes(), compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)


def write_deterministic_bundle(path: Path, repository: Path) -> str:
    """Write the bundle twice from the same immutable input and compare hashes."""
    write_bundle(path, repository)
    probe = path.with_name(f".{path.name}.determinism-check")
    try:
        write_bundle(probe, repository)
        bundle_hash = digest(path, "sha256")
        if bundle_hash != digest(probe, "sha256"):
            raise ValidationError("deterministic bundle check failed: two normalized ZIPs differ")
        return bundle_hash
    finally:
        probe.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", required=True, type=Path)
    parser.add_argument("--write-checksums", action="store_true")
    parser.add_argument("--require-signatures", action="store_true")
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--bundle", type=Path)
    parser.add_argument("--plugin-source", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repository = args.repository.resolve()
    try:
        if args.write_checksums:
            write_checksums(repository)
        report = validate_repository(repository, args.require_signatures, args.plugin_source)
        if args.manifest:
            write_manifest(args.manifest, repository, report)
        bundle_hash = None
        if args.bundle:
            bundle_hash = write_deterministic_bundle(args.bundle, repository)
    except ValidationError as error:
        print(f"G008 publication validation: FAIL: {error}", file=sys.stderr)
        return 1
    print(
        json.dumps(
            {
                "status": "PASS",
                "coordinates": report["coordinates"],
                "signature_mode": "required" if args.require_signatures else "unsigned-local-smoke",
                "bundle_sha256": bundle_hash,
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
