// Modified by Leminity from the upstream Realm Java project.
buildscript {
    def properties = new Properties()
    properties.load(new FileInputStream("${projectDir}/../dependencies.list"))

    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
}

apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'io.github.leminity.realm'
version = file("${projectDir}/../version.txt").text.trim()

apply from: "${rootDir}/../mavencentral-publications.gradle"

publishing {
    publications {
        realm(MavenPublication) {
            groupId 'io.github.leminity.realm'
            artifactId = 'realm-annotations'
            from components.java
            populatePom(
                    it,
                    'realm-annotations',
                    'Annotations for Realm. Realm is a mobile database: Build better apps, faster.'
            )
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

javadoc {
    options.encoding = 'UTF-8'
}
